# -*- coding: utf-8 -*-
# Generated by Django 6.0.2 on 2026-02-24 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='如 "CNC-高光机-001"，用于前端列表展示', max_length=50, verbose_name='设备名称')),
                ('device_type', models.CharField(blank=True, help_text='区分不同加工精度的机床，可为空', max_length=50, null=True, verbose_name='设备型号')),
                ('standard_capacity', models.IntegerField(help_text='单位时间内理论最大产出数，用于计算 OEE 性能稼动率', verbose_name='标准产能')),
                ('current_status', models.CharField(choices=[('Running', '运行'), ('Idle', '待机'), ('Down', '停机')], default='Idle', help_text='Running=运行 | Idle=待机 | Down=停机，用于大屏状态指示灯', max_length=20, verbose_name='运行状态')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'db_table': 'device_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='数据采集时间，用于 ECharts 时序波形图渲染', verbose_name='采集时间')),
                ('spindle_current', models.FloatField(help_text='对应 Kaggle: S1_CurrentFeedback | ML 特征 X1 | 刀具磨损时切削阻力增大，电流升高', verbose_name='主轴反馈电流 (A)')),
                ('spindle_power', models.FloatField(help_text='对应 Kaggle: S1_OutputPower | ML 特征 X2', verbose_name='主轴输出功率 (W)')),
                ('feed_velocity', models.FloatField(help_text='对应 Kaggle: X1_ActualVelocity | ML 特征 X3 | 反映切削过程动态稳定性', verbose_name='X轴实际进给速度 (mm/min)')),
                ('machining_process', models.CharField(choices=[('Prep', '准备阶段'), ('Layer 1 Up', '第1层切削-上行'), ('Layer 1 Down', '第1层切削-下行'), ('Layer 2 Up', '第2层切削-上行'), ('Layer 2 Down', '第2层切削-下行'), ('Layer 3 Up', '第3层切削-上行'), ('Layer 3 Down', '第3层切削-下行'), ('end', '结束')], db_index=True, default='Layer 1 Up', help_text='对应 Kaggle: Machining_Process | 用于 ML 数据清洗，剔除 Prep/end 等空转期干扰', max_length=50, verbose_name='加工阶段')),
                ('tool_condition', models.BooleanField(db_index=True, default=False, help_text='对应 Kaggle: tool_condition | False=未磨损(Unworn) / True=已磨损(Worn) | 逻辑回归预测目标', verbose_name='刀具磨损状态 (Y)')),
                ('loading_time', models.FloatField(help_text='设备计划运行总时间，用于计算 OEE 时间稼动率', verbose_name='负荷时间 (分钟)')),
                ('downtime', models.FloatField(default=0.0, help_text='负荷时间内因异常停机的时间，用于计算 OEE 时间稼动率', verbose_name='停机时间 (分钟)')),
                ('input_qty', models.IntegerField(help_text='该周期投入生产的物料总数，合格率计算分母', verbose_name='投入数量')),
                ('actual_output', models.IntegerField(default=0, help_text='实际产出数量，用于大屏产量看板及 OEE 性能稼动率计算', verbose_name='实际产量')),
                ('device', models.ForeignKey(help_text='数据来源的 CNC 设备', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_records', to='monitor.deviceinfo', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '生产传感流水',
                'verbose_name_plural': '生产传感流水',
                'db_table': 'production_sensor_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='预警触发时间')),
                ('alert_type', models.CharField(choices=[('LR_TOOL_WEAR', 'LR 模型刀具磨损预警'), ('HIGH_CURRENT', '主轴过电流物理报警'), ('HIGH_POWER', '主轴过载物理报警'), ('LOW_VELOCITY', '进给速度骤降报警'), ('DOWNTIME', '停机超时报警'), ('OTHER', '其他')], db_index=True, default='OTHER', help_text='区分报警来源，用于前端分布图表（饼图/雷达图）分类', max_length=50, verbose_name='报警类型')),
                ('anomaly_score', models.FloatField(blank=True, help_text='LR 模型输出的"刀具磨损概率"（0~1），超过 0.7 触发预警', null=True, verbose_name='异常置信度')),
                ('is_handled', models.BooleanField(db_index=True, default=False, help_text='False=未处理（大屏红色闪烁）| True=已处理（闭环完成）', verbose_name='是否已处理')),
                ('record', models.ForeignKey(help_text='触发报警时的具体电流、功率等现场数据来源', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.productionsensordata', verbose_name='关联流水记录')),
            ],
            options={
                'verbose_name': '异常预警记录',
                'verbose_name_plural': '异常预警记录',
                'db_table': 'anomaly_alert_log',
                'ordering': ['-alert_time'],
            },
        ),
        migrations.AddIndex(
            model_name='productionsensordata',
            index=models.Index(fields=['device', 'timestamp'], name='production__device__5afe34_idx'),
        ),
        migrations.AddIndex(
            model_name='productionsensordata',
            index=models.Index(fields=['machining_process', 'tool_condition'], name='production__machini_e49fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalertlog',
            index=models.Index(fields=['alert_type', 'is_handled', 'alert_time'], name='anomaly_ale_alert_t_868eb4_idx'),
        ),
    ]
