# Generated by Django 6.0.2 on 2026-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_realtime_active', models.BooleanField(default=False, help_text='True=开启实时模拟写入 | False=暂停（不删除历史数据）', verbose_name='实时数据流开关')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_config',
            },
        ),
    ]
