# -*- coding: utf-8 -*-
# Generated by Django 6.0.2 on 2026-02-26 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_systemconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='current_group_id',
            field=models.IntegerField(default=1, help_text='取值 1~5，由重置逻辑变更为 2(准新) 实现回春', verbose_name='当前特征组 ID'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_alert_threshold',
            field=models.FloatField(default=0.75, verbose_name='AI 置信度高报阈值'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='feed_velocity_low',
            field=models.FloatField(default=0.5, verbose_name='进给速度低报阈值(mm/min)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='spindle_current_high',
            field=models.FloatField(default=50.0, verbose_name='主轴电流高报阈值(A)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='spindle_power_high',
            field=models.FloatField(default=120.0, verbose_name='主轴功率高报阈值(W)'),
        ),
        migrations.AlterField(
            model_name='anomalyalertlog',
            name='anomaly_score',
            field=models.FloatField(blank=True, help_text='LR 模型输出的"刀具磨损概率"（0~1），超过 0.75 触发预警', null=True, verbose_name='异常置信度'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('job_number', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Engineer', 'Engineer'), ('Operator', 'Operator')], default='Operator', max_length=20, verbose_name='系统角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联系统用户')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
