# Generated by Django 6.0.2 on 2026-03-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_deviceinfo_current_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='defect_buffer',
            field=models.FloatField(default=0.0, help_text='实时流计算时持久化存放的次品小数余数', verbose_name='次品累加器'),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='yield_buffer',
            field=models.FloatField(default=0.0, help_text='实时流计算时持久化存放的良品小数余数', verbose_name='产量累加器'),
        ),
    ]
