# Generated by Django 6.0.2 on 2026-03-11 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_deviceinfo_defect_buffer_deviceinfo_yield_buffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('message', models.TextField(verbose_name='日志内容')),
                ('log_type', models.CharField(default='engine_log', max_length=20, verbose_name='日志类型')),
            ],
            options={
                'verbose_name': '引擎日志',
                'verbose_name_plural': '引擎日志',
                'db_table': 'system_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
