# Generated by Django 6.0.2 on 2026-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='maintenance_advice',
            field=models.TextField(default='设备运行平稳，暂无维修建议。', help_text='下发维修工单时填写的建议文本，将实时同步至数字孪生面板', verbose_name='维修建议/工单说明'),
        ),
    ]
