# Generated by Django 6.0.2 on 2026-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_deviceinfo_maintenance_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsensordata',
            name='anomaly_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='[V3.4.6] 持久化存放该时刻的模型推断值，确保详情页与 Dashboard 逻辑 1:1 同步', verbose_name='异常风险分'),
        ),
        migrations.AlterField(
            model_name='anomalyalertlog',
            name='alert_type',
            field=models.CharField(choices=[('LR_TOOL_WEAR', 'LR 模型刀具磨损预警'), ('HIGH_CURRENT', '主轴过电流物理报警'), ('HIGH_POWER', '主轴过载物理报警'), ('LOW_VELOCITY', '进给速度骤降报警'), ('OTHER', '其他')], db_index=True, default='OTHER', help_text='区分报警来源，用于前端分布图表（饼图/雷达图）分类', max_length=50, verbose_name='报警类型'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='is_realtime_active',
            field=models.BooleanField(default=True, help_text='True=开启实时模拟写入 | False=暂停（不删除历史数据）', verbose_name='实时数据流开关'),
        ),
    ]
